name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build project
      run: cmake --build build

    # ========== ТЕСТЫ ==========
    - name: Run tests (ctest)
      run: |
        cd build
        ctest --output-on-failure

    - name: Run test executable directly
      run: ./build/test_hamburger

    # ========== DEB ПАКЕТ ==========
    - name: Create deb package with CPack
      run: |
        cd build
        cpack -G DEB

    - name: Upload deb as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rk2-builder-deb
        path: build/*.deb

    # ========== RELEASE ==========
    - name: Create Release and upload deb
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
